### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by projectPythonator** [hanyangii/DelaunayTriangulation2D#1]
My name is Agis Daniels and I was wondering if I could use this code to as a translation template for a python cheatsheet I am building?
If so how would you like me to cite this code?

**Comment by hanyangii** [comment]
Hello, 



Thanks for getting in touch to me. 

I am sorry for late reply. As the email was not in a mailbox I mainly use, I couldn't see your comment. 

I am happy to provide my code in your cheatsheet!

I have no idea what kind of citation format would be good for your purpose.

Could you please briefly introduce the cheatsheet and other examples of citation in your cheatsheet?
